import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const Skills = () => {
    return (_jsxs("div", { className: "container mx-auto px-6", children: [_jsxs("div", { className: "text-center mb-12 animate-slide-up", children: [_jsx("h2", { className: "text-3xl md:text-4xl font-bold font-heading mb-4", children: "Skills & Expertise" }), _jsx("p", { className: "text-text-muted text-lg max-w-2xl mx-auto", children: "Technologies and tools I use to bring ideas to life" })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-8", children: [_jsx("div", { className: "animate-slide-up", style: { animationDelay: "0.1s" }, children: _jsxs("div", { className: "bg-background p-6 rounded-2xl border border-border h-full", children: [_jsxs("div", { className: "flex items-center space-x-3 mb-6", children: [_jsx("div", { className: "w-12 h-12 rounded-lg bg-primary bg-opacity-20 flex items-center justify-center", children: _jsx("i", { className: "fab fa-react text-primary text-xl" }) }), _jsx("h3", { className: "text-xl font-semibold", children: "Frontend" })] }), _jsx("div", { className: "space-y-4", children: [
                                        { label: "React", value: 95 },
                                        { label: "TypeScript", value: 50 },
                                        { label: "Tailwind CSS", value: 92 },
                                        { label: "Bootstrap", value: 88 },
                                    ].map((item) => (_jsxs("div", { children: [_jsxs("div", { className: "flex justify-between mb-1", children: [_jsx("span", { className: "text-text-muted", children: item.label }), _jsxs("span", { className: "text-primary", children: [item.value, "%"] })] }), _jsx("div", { className: "w-full bg-background rounded-full h-2", children: _jsx("div", { className: "skill-bar bg-primary rounded-full h-2", style: { width: `${item.value}%` } }) })] }, item.label))) })] }) }), _jsx("div", { className: "animate-slide-up", style: { animationDelay: "0.2s" }, children: _jsxs("div", { className: "bg-background p-6 rounded-2xl border border-border h-full", children: [_jsxs("div", { className: "flex items-center space-x-3 mb-6", children: [_jsx("div", { className: "w-12 h-12 rounded-lg bg-secondary bg-opacity-20 flex items-center justify-center", children: _jsx("i", { className: "fas fa-server text-secondary text-xl" }) }), _jsx("h3", { className: "text-xl font-semibold", children: "Backend" })] }), _jsx("div", { className: "space-y-4", children: [
                                        { label: "Python", value: 90 },
                                        { label: "Django", value: 85 },
                                        { label: ".NET Core", value: 82 },
                                        { label: ".NET Framework (ASPX)", value: 80 },
                                        { label: "REST APIs", value: 95 },
                                    ].map((item) => (_jsxs("div", { children: [_jsxs("div", { className: "flex justify-between mb-1", children: [_jsx("span", { className: "text-text-muted", children: item.label }), _jsxs("span", { className: "text-primary", children: [item.value, "%"] })] }), _jsx("div", { className: "w-full bg-background rounded-full h-2", children: _jsx("div", { className: "skill-bar bg-primary rounded-full h-2", style: { width: `${item.value}%` } }) })] }, item.label))) })] }) }), _jsx("div", { className: "animate-slide-up", style: { animationDelay: "0.3s" }, children: _jsxs("div", { className: "bg-background p-6 rounded-2xl border border-border h-full", children: [_jsxs("div", { className: "flex items-center space-x-3 mb-6", children: [_jsx("div", { className: "w-12 h-12 rounded-lg bg-orange-500 bg-opacity-20 flex items-center justify-center", children: _jsx("i", { className: "fas fa-tools text-orange-500 text-xl" }) }), _jsx("h3", { className: "text-xl font-semibold", children: "Tools & Others" })] }), _jsx("div", { className: "space-y-4", children: [
                                        { label: "Git & GitHub", value: 90 },
                                        { label: "Visual Studio", value: 95 },
                                        { label: "Azure DevOps", value: 80 },
                                        { label: "VS Code", value: 98 },
                                    ].map((item) => (_jsxs("div", { children: [_jsxs("div", { className: "flex justify-between mb-1", children: [_jsx("span", { className: "text-text-muted", children: item.label }), _jsxs("span", { className: "text-primary", children: [item.value, "%"] })] }), _jsx("div", { className: "w-full bg-background rounded-full h-2", children: _jsx("div", { className: "skill-bar bg-primary rounded-full h-2", style: { width: `${item.value}%` } }) })] }, item.label))) })] }) })] })] }));
};
export default Skills;
